### PR TITLE
RC 1.0.5

### PR DESCRIPTION
**Pull request by EmilHvitfeldt**
to close https://github.com/tidymodels/textrecipes/issues/250

### CODE REVIEW

**Comment by aitap** [comment]
Your CPU time problems are likely caused by `text2vec` [using `parallel::mcparallel`](https://github.com/dselivanov/text2vec/blob/e3b9865057ba8dae713badbf71ca5160b7a6efa6/R/mc_queue.R#L3-L20) in addition to `data.table`. This definitely needs to be reported to the `text2vec` maintainer because of their default of `parallel::detectCores()`, which CRAN doesn't like any more. As a workaround, you can set `options(text2vec.mc.cores=...)` for the duration of the example.

**Comment by aitap** [comment]
I'm sorry it didn't help. I see you're using library(text2vec) and only
then options("text2vec.mc.cores" = 1). This is the most careful way
(text2vec:::.onLoad resets the option!); if text2vec.mc.cores was the
culprit, your fix would have worked.

Another option I tried was to patch parallel::detectCores() to always
return a large number and then run R CMD check on your package with the
_R_CHECK_EXAMPLE_TIMING_CPU_TO_ELAPSED_THRESHOLD_=2 environment
variable and the --timings flag set. I couldn't reproduce it either. I
do get CPU time ~1.3 times elapsed time for the step_dummy_hash
example, but (1) only because I have parallel OpenBLAS installed and
(2) 1.3 times is too low to trigger the NOTE.

**Comment by aitap** [comment]
I've set a breakpoint on pthread_create in gdb and ran
example(step_dummy_hash). The breakpoint fired multiple times; the
unexpected hits were in rsparse's omp_thread_count() [1] where it
eventually set options(rsparse_omp_threads) [2] to the number of
logical processors on my virtual machine.

I think that rsparse:::.onLoad gets to run (and decide to use the whole
CPU) before you set OMP_THREAD_LIMIT because rlang::is_installed calls
requireNamespace. Putting the Sys.setenv() call above the call to
rlang::is_installed() should circumvent the problem.

[1]
https://github.com/rexyai/rsparse/blob/873db8474c09e6974404e65868a712af8d834fb0/src/utils.cpp#L80-L91

[2]
https://github.com/rexyai/rsparse/blob/873db8474c09e6974404e65868a712af8d834fb0/R/zzz.R#L27

**Comment by EmilHvitfeldt** [comment]
@aitap Thank you so much for looking into this! Would you be able to teach me what you did to gain those insights? I'm fine if you don't, you already helped me so much!

**Comment by aitap** [comment]
My first idea was that if something takes too much CPU time, it [ought to show up in the CPU profiler](https://stat.ethz.ch/pipermail/r-package-devel/2023q4/009751.html). [Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html#Profiling-compiled-code) mentions a few profiling techniques. I've heard good things about Intel's VTune profiler (on both GNU/Linux and Windows) and [Very Sleepy](http://www.codersnotes.com/sleepy/) on Windows. The [section on profiling in Algorithmica](https://en.algorithmica.org/hpc/profiling/) is a bit terse but contains useful pointers. I'm using [`perf`](https://perf.wiki.kernel.org/index.php/Main_Page) on GNU/Linux because it's easy to install and doesn't require any instrumentation of the executables besides compiling with `-g` (which R already does). In the end, the traces I got for `system.time(replicate(100, example(step_dummy_hash)))` didn't give any obvious pointers, but I did consistently see 1.3 times of CPU time consumed per unit of real time. The CRAN machine has a different processor; maybe threads are more expensive in their circumstances?

I'm using [an accelerated BLAS](https://www.openblas.net/) that can start threads on its own, so I was ready to blame OpenBLAS for the threads, but even with [the environment variable `OPENBLAS_NUM_THREADS=1` set](https://github.com/OpenMathLib/OpenBLAS/wiki/Faq#multi-threaded) I could see more than 100% of one CPU core being used (as measured by `system.time`).

If threads do evidently consume extra CPU time, perhaps some information could be gained by seeing who creates them? [The OpenMP specification](https://www.openmp.org/wp-content/uploads/OpenMP-API-Specification-5.0.pdf) is not 100% precise on this, but it makes sense for a program to start new threads when it encounters a `#pragma omp parallel` directive and stop them when they are done. I've read [Butenhof, 1997](https://openlibrary.org/books/OL661201M/Programming_with_POSIX_threads) and decided to [set a breakpoint](https://beej.us/guide/bggdb/#breakpoints) on `pthread_create`, the function used to start threads on POSIX-compatible operating systems. The OpenMP runtime implementors could have used a system-specific call (e.g. [clone(2)](https://man7.org/linux/man-pages/man2/clone.2.html) on Linux), but they did use `pthread_create`, so the breakpoints fired in appropriate places. 

The [`omp_thread_count()`](https://github.com/rexyai/rsparse/blob/873db8474c09e6974404e65868a712af8d834fb0/src/utils.cpp#L80-L91) function was surprising because it looks like an OpenMP API but is not. The author could have used `omp_get_thread_limit` instead of creating a parallel section just to run `omp_get_num_threads` or counting threads one by one. The involvement of `rsparse` was not 100% conclusive (maybe there's a third package that also creates threads that I haven't noticed yet?), but it was definitely worth trying to limit the number of threads used by this package.

**Pull request merged**
