### PR TITLE
Implementing step_word_embeddings. Closes #20.

### LINKED ISSUE #20: Word embeddings
I want to include word embedding steps in this package at some point.

Asked in https://github.com/tidymodels/textrecipes/issues/9 I'm going to answer here in the main issue.

I would like to have a step for each word embedding we implement. I want this approach because I fear that a general `step_embed` would end up with a lot of arguments as each embedding might need different arguments.

As of right now the https://github.com/dselivanov/text2vec package is already imported and it allows for both text2vec and Glove so it would be a nice place to start. Later we can look at other embeddings such as fasttext which would require additional dependencies.

We would like to have some default pre-trained embeddings (for sure), but in the future it would also be nice for some custom trained embeddings to be used. Some investigation on the correct format would have to be done.
The priority right now is to have the embeddings working, and then we can implement user-supplied embeddings after.

### PR DESCRIPTION
**Pull request by jonthegeek**
In progress. Just wanted to let you see the structure I'm aiming for as I work on this.

### CODE REVIEW

**Comment by jonthegeek** [comment]
Updating to step_word_embeddings to leave room for other types of embeddings.

**Comment by EmilHvitfeldt** [comment]
Just a quick note:

**textdata** cannot be used within examples or tests since it doesn't work without a human in the loop in places such as travis or CRAN.

We can handmade a smaller embedding

```
mini_glove <- tibble(token = c("a", "whole", "embedding"),
                     d1 = c(0, 1, 0),
                     d2 = c(0.6, 0.3, -0.7))
```

**Comment by jonthegeek** [comment]
The textdata call is commented out because that's how I built sample data, which is saved as an rds in the testthat folder; I just wanted users to be able to see where it came from. I'll likely further minimize it, but for now I grabbed a full "real" set of vectors for the words in the tests.

**Comment by EmilHvitfeldt** [comment]
perfect!

**Comment by jonthegeek** [comment]
To deal with: storing the embeddings during prep (mostly shouldn't be a problem, I just forgot to do it yesterday).

A thing I'm thinking about: per @topepo's advice at https://github.com/tidymodels/tune/issues/75, I'm setting this to allow for multiple `step_word_embeddings` calls using different aggregation functions. If they call more than one with the same embeddings, though, ideally I want to make sure R knows it's the same tibble, and doesn't store it multiple times in the prepped object. I mostly need to review some rules and make sure it'll work that way (or figure out a way to force it to reference the same object). This isn't vital for v1, but it could get super ugly with glove840b (4.94GB processed RDS), for example, if you used all 4 allowed aggregation functions and the prepped recipe included the embeddings 4x.

**Comment by jonthegeek** [comment]
Looking back at @topepo's comments about tunable, I *think* I may want/need to implement something(s) here. Still wrapping my head around it/experimenting locally.

**Comment by jonthegeek** [comment]
I also ran into this error (when I filtered things such that one of my input sentences had no remaining words): Error: Tokens missing from embeddings tibble: NA
Going to implement a fix for that at least, and investigate the tunable parameter.

**Comment by EmilHvitfeldt** [comment]
Hello @jonthegeek, sorry about the long wait!! How is this PR going, do you need anything else or is it ready to be merged?

**Comment by jonthegeek** [comment]
I'll update it tomorrow. I've done more work with recipes since I originally worked on this, so I should be able to make sure it's clean.

**Comment by EmilHvitfeldt** [comment]
thank you, no rush! ping me if you need anything from me

**Comment by EmilHvitfeldt** [comment]
Thank you so much for all your work!

**Pull request merged**
